version: "3.8"

services:
  backend:
    build:
      context: ./backend
      args:
        WORKDIR: $WORKDIR
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      API_DOMAIN: "localhost:$FRONT_PORT"
    volumes:
      - ./backend:/$WORKDIR
    ports:
      - "$API_PORT:$CONTAINER_PORT"

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    volumes:
      - ./frontend:/$WORKDIR
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - backend
